In [ ]:
#INSTALANDO BIBLIOTECAS NECESSÁRIAS
!pip install -U sidrapy

import sidrapy
import pandas as pd
import numpy as np

In [2]:
#PEGANDO OS DADOS DE SERGIPE DO GRAFICO G17.2

G17p2_SE = sidrapy.get_table(table_code="356",variable="1887/C1/6795/C2/6794/C58/2795", territorial_level="3", ibge_territorial_code="28", period="all")
G17p2_SE = G17p2_SE.iloc[1:, [8,6,4]]
G17p2_SE.columns = ['ANO','REGIÃO','NÚMERO MÉDIO DE ANOS DE ESTUDO DAS PESSOAS DE 15 ANOS OU MAIS DE IDADE (ANOS)']
G17p2_SE

G17p2_SE_2016 = sidrapy.get_table(table_code="7126",variable="3593/C2/6794/C58/2795", territorial_level="3", ibge_territorial_code="28", period="all")
G17p2_SE_2016 = G17p2_SE_2016.iloc[1:, [8,6,4]]
G17p2_SE_2016.columns = ['ANO','REGIÃO','NÚMERO MÉDIO DE ANOS DE ESTUDO DAS PESSOAS DE 15 ANOS OU MAIS DE IDADE (ANOS)']
G17p2_SE_2016

#PEGANDO OS DADOS DO NORDESTE DO GRAFICO G17.2

G17p2_NE = sidrapy.get_table(table_code="356",variable="1887/C1/6795/C2/6794/C58/2795", territorial_level="2", ibge_territorial_code="2", period="all")
G17p2_NE = G17p2_NE.iloc[1:, [8,6,4]]
G17p2_NE.columns = ['ANO','REGIÃO','NÚMERO MÉDIO DE ANOS DE ESTUDO DAS PESSOAS DE 15 ANOS OU MAIS DE IDADE (ANOS)']
G17p2_NE

G17p2_NE_2016 = sidrapy.get_table(table_code="7126",variable="3593/C2/6794/C58/2795", territorial_level="2", ibge_territorial_code="2", period="all")
G17p2_NE_2016 = G17p2_NE_2016.iloc[1:, [8,6,4]]
G17p2_NE_2016.columns = ['ANO','REGIÃO','NÚMERO MÉDIO DE ANOS DE ESTUDO DAS PESSOAS DE 15 ANOS OU MAIS DE IDADE (ANOS)']
G17p2_NE_2016

#PEGANDO OS DADOS DO BRASIL DO GRAFICO G17.2

G17p2_BR = sidrapy.get_table(table_code="356",variable="1887/C1/6795/C2/6794/C58/2795", territorial_level="1", ibge_territorial_code="1", period="all")
G17p2_BR = G17p2_BR.iloc[1:, [8,6,4]]
G17p2_BR.columns = ['ANO','REGIÃO','NÚMERO MÉDIO DE ANOS DE ESTUDO DAS PESSOAS DE 15 ANOS OU MAIS DE IDADE (ANOS)']
G17p2_BR

G17p2_BR_2016 = sidrapy.get_table(table_code="7126",variable="3593/C2/6794/C58/2795", territorial_level="1", ibge_territorial_code="1", period="all")
G17p2_BR_2016 = G17p2_BR_2016.iloc[1:, [8,6,4]]
G17p2_BR_2016.columns = ['ANO','REGIÃO','NÚMERO MÉDIO DE ANOS DE ESTUDO DAS PESSOAS DE 15 ANOS OU MAIS DE IDADE (ANOS)']
G17p2_BR_2016

# JUNTANDO TODAS AS TABELA

G17P2 = pd.concat([G17p2_SE,G17p2_SE_2016,G17p2_NE,G17p2_NE_2016,G17p2_BR,G17p2_BR_2016])

#CONFIGURANDO OS TIPOS DE ARQUIVO DAS VARIÁVEIS
G17P2['ANO'] = G17P2['ANO'].astype(np.int64)
G17P2['NÚMERO MÉDIO DE ANOS DE ESTUDO DAS PESSOAS DE 15 ANOS OU MAIS DE IDADE (ANOS)'] = G17P2['NÚMERO MÉDIO DE ANOS DE ESTUDO DAS PESSOAS DE 15 ANOS OU MAIS DE IDADE (ANOS)'].astype(float)

#EXPORTANDO (CSV E EXCEL)
G17P2.to_csv('G17_2.csv', sep=';', index=False, encoding='latin1', decimal=',')
G17P2.to_excel('G17_2.xlsx', index=False,)

# VISUALIZANDO
G17P2

,ANO,REGIÃO,NÚMERO MÉDIO DE ANOS DE ESTUDO DAS PESSOAS DE 15 ANOS OU MAIS DE IDADE (ANOS)
1,2005,Sergipe,5.9
2,2006,Sergipe,6.1
1,2016,Sergipe,8.3
2,2017,Sergipe,8.4
3,2018,Sergipe,8.4
4,2019,Sergipe,8.6
5,2022,Sergipe,8.9
1,2005,Nordeste,5.6
2,2006,Nordeste,5.8
1,2016,Nordeste,8.2
2,2017,Nordeste,8.3
3,2018,Nordeste,8.5
4,2019,Nordeste,8.7
5,2022,Nordeste,8.9
1,2005,Brasil,7.0
2,2006,Brasil,7.2
1,2016,Brasil,9.4
2,2017,Brasil,9.5
3,2018,Brasil,9.7
4,2019,Brasil,9.8
5,2022,Brasil,10.1

In [ ]:
#PEGANDO OS DADOS DE SERGIPE DO GRAFICO T16.2

T16p2_SE = sidrapy.get_table(table_code="6677",variable="10250/C845/47552,47553,47554,47555,47556", territorial_level="3", ibge_territorial_code="28", period="all")
T16p2_SE = T16p2_SE.iloc[1:, [8,6,12,4]]
T16p2_SE.columns = ['ANO','REGIÃO','POSSE DE BENS','PERCENTUAL DE DOMICÍLIOS']
T16p2_SE

#PEGANDO OS DADOS DO NORDESTE DO GRAFICO T16.2

T16p2_NE = sidrapy.get_table(table_code="6677",variable="10250/C845/47552,47553,47554,47555,47556", territorial_level="2", ibge_territorial_code="2", period="all")
T16p2_NE = T16p2_NE.iloc[1:, [8,6,12,4]]
T16p2_NE.columns = ['ANO','REGIÃO','POSSE DE BENS','PERCENTUAL DE DOMICÍLIOS']
T16p2_NE

#PEGANDO OS DADOS DO BRASIL DO GRAFICO T16.2

T16p2_BR = sidrapy.get_table(table_code="6677",variable="10250/C845/47552,47553,47554,47555,47556", territorial_level="1", ibge_territorial_code="1", period="all")
T16p2_BR = T16p2_BR.iloc[1:, [8,6,12,4]]
T16p2_BR.columns = ['ANO','REGIÃO','POSSE DE BENS','PERCENTUAL DE DOMICÍLIOS']
T16p2_BR

# JUNTANDO TODAS AS TABELA

T16P2 = pd.concat([T16p2_SE, T16p2_NE,T16p2_BR,])

#CONFIGURANDO OS TIPOS DE ARQUIVO DAS VARIÁVEIS
T16P2['ANO'] = T16P2['ANO'].astype(np.int64)
T16P2['PERCENTUAL DE DOMICÍLIOS'] = T16P2['PERCENTUAL DE DOMICÍLIOS'].astype(float)

#EXPORTANDO (CSV E EXCEL)
T16P2.to_csv('tabela_T16_2.csv', sep=';', index=False, encoding='latin1', decimal=',')
T16P2.to_excel('tabela_T16_2.xlsx', index=False,)

# VISUALIZANDO
T16P2